server.port : 8081
spring:
  h2:
    console:
      path: '/h2'
      enabled: true
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE'
    username: 'admin'
    password: 'admin'
  data:
    rest:
      base-path: 'api'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.H2Dialect'
management:
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    shutdown:
      enabled: true