server.port : 8081
spring:
  profiles:
    active: 'local'
  datasource:
    platform: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
  data:
    rest:
      base-path: 'api'
  jpa:
    hibernate:
      ddl-auto: update
    database: 'POSTGRESQL'
management:
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    shutdown:
      enabled: true